language: go
matrix:
  include:
  - go: "1.11.x"
    env: RACE=TRUE USE_LINT=TRUE
  - go: "1.11.x"
    env: RACE=FALSE USE_LINT=TRUE
  - go: "1.10.x"
    env: RACE=TRUE USE_LINT=FALSE
  - go: "1.10.x"
    env: RACE=FALSE USE_LINT=FALSE
sudo: required
install:
  - sudo add-apt-repository -y ppa:bitcoin/bitcoin -y
  - sudo apt-get update -q
  - sudo apt-get install bitcoind -y
  - export PATH=$PATH:$PWD/linux-amd64/
script:
  - export PATH=$PATH:$GOPATH/bin
  - make travis
after_script:
  - echo "Uploading to termbin.com..." && find *.log | xargs -I{} sh -c "cat {} | nc termbin.com 9999 | xargs -r0 printf '{} uploaded to %s'"
  - echo "Uploading to file.io..." && tar -zcvO *.log | curl -s -F 'file=@-;filename=logs.tar.gz' https://file.io | xargs -r0 printf 'logs.tar.gz uploaded to %s\n'
